In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.7 MB 4.8 MB/s eta 0:00:03
   ------ --------------------------------- 2.1/12.7 MB 4.6 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.7 MB 4.6 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.7 MB 4.5 MB/s eta 0:00:02
   -------------- ------------------------- 4.7/12.7 MB 4.3 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.7 MB 4.3 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.7 MB 4.5 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.7 MB 3.9 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.7 MB 4.0 MB/s eta 0:00:02
   ---------------------------- ----------- 9.2/12.7 MB 4.3 MB/s eta 0:00:01
   ---------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [1]:
import numpy as np

In [2]:
# creatinng array 
arr =np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [3]:
print (np.__version__)

2.3.1


In [4]:
arr2=np.array([1,2,3,4,5,6])
print(arr2)
print(type(arr2))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [5]:
arr=np.array(42)
print(arr)

42


In [6]:
arr=np.array([[1,2,3,4,5,6]])
print(arr)

[[1 2 3 4 5 6]]


In [7]:
arr = np.array([1,2,3])
for x in arr:
 print(x)

1
2
3


In [8]:
# Accessing elements for -ve index
arr=np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
print(arr[0,-2])

4


In [9]:
# slicing elements from array 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[1:11:2])

[ 2  4  6  8 10]


In [10]:
# slicing with -ve
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[-5:-1])

[6 7 8 9]


In [11]:
# checking datatype of array 

arr =np.array([1,2,3,4,5])
print(arr.dtype) 

int64


In [12]:
# checking shape of an array 

arr=np.array([[1,2,3,4],
             [5,6,7,8]])
print(arr.shape)

(2, 4)


In [13]:
# checking size of an array 
arr=np.array([[1,2,3,4],
             [5,6,7,8]])
print(arr.size)

8


In [14]:
# Reshaping arrays 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
# Joining array 
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [16]:
# spiling of an array 

arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,6)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [17]:
# searching for indexing an array 
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)

(array([3, 5, 6]),)


In [18]:
# sorting array 
# ascending order

arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [19]:
# descending order

arr=np.array([3,2,0,1])
print(np.sort(arr)[::-1])

[3 2 1 0]


In [20]:
# flitering array elemets

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [21]:
arr = np.array([41, 42, 43, 44])
filter_arr = []  

for element in arr:  
    if element > 42:                 
        filter_arr.append(True)
    else:
        filter_arr.append(False)    

newarr = arr[filter_arr]
print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]


In [22]:
# conversion of datatype 
arr=np.array([1.0,2.7,3.6,4,5])
print(arr.dtype)
print(arr.astype(str))

float64
['1.0' '2.7' '3.6' '4.0' '5.0']


In [23]:
# adding and removing elements
arr=np.array([20,30,40,50])
# append 
print(np.append(arr,60))

[20 30 40 50 60]


In [24]:
# insert 
print (np.insert(arr,3,60))

[20 30 40 60 50]


In [25]:
# delete
print(np.delete(arr,[2]))

[20 30 50]


In [26]:
# aggregating function 

a =np.array([10,20,30,40,50,60])

# sum 
print(np.sum(a))

210


In [27]:
#minimum
print(np.min(a))

10


In [28]:
#mazimum
print(np.max(a))

60


In [29]:
# cumulative sum 
print(np.cumsum(arr))

[ 20  50  90 140]


In [30]:
# statistics as starts 

food_price=[10,20,50,60,70,20,20,30]
arr=np.array(food_price)

# mean 
print(np.mean(arr))

35.0


In [31]:
 #median
print(np.median(arr))

25.0


In [1]:
# mode 
print("Mode:", stats.mode(arr, keepdims=True))



NameError: name 'stats' is not defined